# Generated by Django 4.1.2 on 2023-02-12 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='image',
            new_name='images',
        ),
    ]
